#!/bin/sh
#SBATCH -J pagerank-16           # job name
#SBATCH -o /work/02188/nikunj/multicore/out-16       # output and error file name (%j expands to jobID)
#SBATCH -n 1              # total number of mpi tasks requested
#SBATCH -p development     # queue (partition) -- normal, development, etc.
#SBATCH -t 01:30:00        # run time (hh:mm:ss) - 1.5 hours
ibrun tacc_affinity pagerank 16 /work/02188/nikunj/graphs/USA-road.edgelist
