#!/bin/sh
#SBATCH -J ssp-dj-random
#SBATCH -o /work/02188/nikunj/multicore/parallelStuff/SSSP/ssp-dijkstra
#SBATCH -n 1
#SBATCH -p development
#SBATCH -t 01:30:00
ibrun tacc_affinity /work/02188/nikunj/multicore/parallelStuff/SSSP/src/sssp -v -f /work/02188/nikunj/graphs/USA-road-d.USA.w_edgelist -o /work/02188/nikunj/multicore/parallelStuff/SSSP/ssp-out-dijkstra -algorithm Dijkstra
