#!/bin/sh
#SBATCH -J ssp-serial
#SBATCH -o /work/02188/nikunj/multicore/parallelStuff/SSSP/ssp-bellman-1
#SBATCH -n 1
#SBATCH -p development
#SBATCH -t 01:30:00
ibrun tacc_affinity /work/02188/nikunj/multicore/parallelStuff/SSSP/src/sssp -v -t 1 -f /work/02188/nikunj/graphs/USA-road-d.USA.w_edgelist -o /work/02188/nikunj/multicore/parallelStuff/SSSP/ssp-out-1 -algorithm BellmanFord
